server:
  port: 8080

spring:
  application:
    name: modi-gateway
  config:
    import: "optional:configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: modi-config