spring:
  application:
    name: modi-gateway
  config:
    import: "optional:configserver:http://modi-config/8888"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: modi-config