server:
  port: 8761

spring:
  application:
    name: modi-discovery
#  config:
#    import: optional:configserver:http://modi-config:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


