apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: modi
resources:
  - ../../base
secretGenerator:
  - name: modi-env
    envs:
      - .env
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: gateway-service-nodeport.yaml
