spring:
  application:
    name: review-service
  config:
    import: "optional:configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: modi-config

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}

openai:
  api-key: #추가해야됨
  model: gpt-4.1-mini
  summary:
    max-length: 200

