apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  labels:
    app: delivery-service
spec:
  ports:
    - name: http
      port: 8088
      targetPort: 8088
  selector:
    app: delivery-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  labels:
    app: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: modi/delivery-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8088
          env:
            - name: SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED
              value: "false"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SERVER_PORT
              value: "8088"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: modi-env
                  key: DELIVERY_DB_URL
          envFrom:
            - secretRef:
                name: modi-env
          startupProbe:
            tcpSocket:
              port: 8088
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 8088
            initialDelaySeconds: 10
            periodSeconds: 10
