server:
  port: 8084

spring:
  application:
    name: seller-service
  datasource:
    url: jdbc:postgresql://localhost:5432/seller
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update   # 또는 update, 초기에만 사용 가능
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: ${JWT_SECRET:LkudBWHfiGbZbPdo8pZSFhpiB0kxR4sEuJb4yX2DzApXjgMfrfZhJR}
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000
